### ISSUE TITLE
gpumemusage [error for multi-gpu]

### ISSUE THREAD

**Issue by foolwood** [NVIDIA/flownet2-pytorch#1]
Thanks for sharing your code. 
I notice in README you said "Multiple GPU training is supported". 
But i think this [function](https://github.com/NVIDIA/flownet2-pytorch/blob/4528f57a8a11a2a3a3d7947268f2164e7c69fe35/utils/tools.py#L123) only support for a single gpu computer. I add some code for my personal usage, but I think there are better solutions.

```python
def gpumemusage():
    gpu_mem = subprocess.check_output("nvidia-smi | grep MiB | cut -f 3 -d '|'", shell=True).\
        replace(' ', '').replace('\n', '').replace('i', '').replace('MB', 'MB/').replace('//', '/')
    gpu_mem = gpu_mem[:-1]
    gpu_info= [float(a[:-2]) for a in gpu_mem.split('/')]
    curr = sum(gpu_info[0::2])
    tot = sum(gpu_info[1::2])
    util = "%1.2f"%(100*curr/tot)+'%'
    cmem = str(int(math.ceil(curr/1024.)))+'GB'
    gmem = str(int(math.ceil(tot/1024.)))+'GB'
    gpu_mem = util + '--' + join(cmem, gmem)
    return gpu_mem
```

**Comment by fitsumreda** [comment]
Thanks @foolwood !
That function should now work for any number of gpus.
