### ISSUE TITLE
Is the resample2d function implemented correctly? 

### ISSUE THREAD

**Issue by HaiyongJiang** [NVIDIA/flownet2-pytorch#10]
Dear author. 
       I happened to see the resample2d implementation in "`flownet2-pytorch/networks/resample2d_package/src/Resample2d_kernel.cu`". In line#64, the output is assigned to a sum of values inside a region. Is it more reasonable to be a weighted sum?

**Comment by fitsumreda** [comment]
@HaiyongJiang Yes, we believe line #64 is correct. 
You may ignore the outer nested for loop over `kernel_size`, since the `kernel_size=1` for resample2d.
so, it doesn't do averaging over a region or a patch. 
It is done this way to make the implementation generalizable to other cases.

**Comment by HaiyongJiang** [comment]
Thank you. But what if we set kernel_size>2. What's the potential meaning?
