### ISSUE TITLE
Checkpoint tar file problem

### ISSUE THREAD

**Issue by pawandeep2155** [NVIDIA/flownet2-pytorch#100]
I downloaded checkpoint files for Flownet2 but there is some issue in unzip. Can you please check the tar files once?

**Comment by InnovArul** [comment]
I think, you should load the weights fle as `torch.load(<weights.pth.tar>)`. Maybe the extension is misleading

**Comment by pawandeep2155** [comment]
Thank you, Arul.

**Comment by jiapei100** [comment]
@pawandeep2155 @InnovArul 
Where is the checkpoint tar please? Can you please leave the link?

Thanks...
