### ISSUE TITLE
NameError: name 'validation_loader' is not defined

### ISSUE THREAD

**Issue by maria-ito** [NVIDIA/flownet2-pytorch#103]
Hi, 

I'm trying to train the model according to the readme, however I'm getting the following error:

python main.py --batch_size 8 --model FlowNet2 --loss=L1Loss --optimizer=Adam --optimizer_lr=1e-4 --training_dataset MpiSintelFinal --training_dataset_root /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/MPI-Sintel-complete/training/final/alley1  --validation_dataset MpiSintelClean --validation_dataset_root /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/MPI-Sintel-complete/training/clean/alley1
Parsing Arguments
[...]

Source Code
  Current Git Hash: 2787b3a920416a3d62133b5c07f0efaebd6ba3c3

Initializing Datasets
  [0.000s] Operation finished

Building FlowNet2 model
  [2.188s] Effective Batch Size: 8
  [2.189s] Number of parameters: 162518834
  [2.189s] Initializing CUDA
  [3.603s] Parallelizing
  [3.605s] Random initialization
  [3.605s] Initializing save directory: ./work
  [3.606s] Operation finished

Initializing Adam Optimizer
  [0.001s] lr = 0.0001 (<type 'float'>)
  [0.001s] amsgrad = False (<type 'bool'>)
  [0.001s] weight_decay = 0 (<type 'int'>)
  [0.001s] betas = (0.9, 0.999) (<type 'tuple'>)
  [0.001s] eps = 1e-08 (<type 'float'>)
  [0.001s] Operation finished

Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 407, in <module>
    validation_loss, _ = train(args=args, epoch=epoch - 1, start_iteration=global_iteration, data_loader=validation_loader, model=model_and_loss, optimizer=optimizer, logger=validation_logger, is_validate=True, offset=offset)
NameError: name 'validation_loader' is not defined
Exception KeyError: KeyError(<weakref at 0x7f2ed3c140a8; to 'tqdm' at 0x7f2ea7bca810>,) in <bound method tqdm.__del__ of Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]> ignored

Can anyone tell me what I'm doing wrong?
Cheers

**Comment by JuanFMontesinos** [comment]
Can you try to point the paths to the main folder? Both to this one
/media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/MPI-Sintel-complete/training

**Comment by maria-ito** [comment]
Thanks! It partially worked. I'll open another issue with the new error

Cheers

**Comment by JuanFMontesinos** [comment]
Well, in fact it's not an error itself. They just expect files to have the single structure but if u put any folder in whatever path but having your data inside a final and clean folders it should work. They just look for the final folder and takes it as the folder which contains the dataset. You can rewrite dataset function to fit your necessities

**Comment by ybcr7** [comment]
> Well, in fact it's not an error itself. They just expect files to have the single structure but if u put any folder in whatever path but having your data inside a final and clean folders it should work. They just look for the final folder and takes it as the folder which contains the dataset. You can rewrite dataset function to fit your necessities

I had point to the main folder, but it still doesn't work. 
python main.py --batch_size 8 --model FlowNet2 --loss=L1Loss --optimizer=Adam --optimizer_lr=1e-4 --training_dataset Mpi
SintelFinal --training_dataset_root /C:/Users/YBCR7/PycharmProjects/flownet2-pytorch/MPI-Sintel-complete/training --validation_dataset MpiSintelClean --validation_dataset_root /C:/Users/YBCR7/PycharmProjects/flownet2-pytorch/MPI-Sintel-complete/training

**Comment by AjithPanja** [comment]
@ybcr7 Any solution to this issue ?
