### ISSUE TITLE
Could you please tell me why I meet this problem?

### ISSUE THREAD

**Issue by TaowzzZ** [NVIDIA/flownet2-pytorch#108]
When I use inference,I get this problem:
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    args.current_hash = subprocess.check_output(["git", "rev-parse", "HEAD"]).rstrip()
  File "/home/t907/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/t907/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

I am a beginner,could you tell how can I solve this problem， please！

**Comment by AziziShekoofeh** [comment]
@TaowzzZ Did you find the reason for this issue? I am heading the same problem but I cannot find the reason.

**Comment by PlanNoa** [comment]
@TaowzzZ @AziziShekoofeh  I met same problem too. Did you solve this issue?

**Comment by sssssyf** [comment]
Did you find the reason for this issue? I am heading the same problem but I cannot find the reason. Thanks.

**Comment by PlanNoa** [comment]
@sssssyf   it is occered by project version check problem. just remove those lines to solve them..

**Comment by DonaldKam** [comment]
Hi @PlanNoa , I also get stucked at this problem. Could you plz make your solution clearer？
Hi@sssssyf @AziziShekoofeh ，have you handled this problem, if yes, could you tell me your solution？

**Comment by PlanNoa** [comment]
@DonaldKam remove line 111, 123, 124 than you will able to use flownet2.

**Comment by GUWOGANSHOU** [comment]
> @DonaldKam remove line 111, 123, 124 than you will able to use flownet2.

Thanks！

**Comment by uchiha99999** [comment]
remove these lines from which file? @PlanNoa

**Comment by PlanNoa** [comment]
@uchiha99999 from main.py
