### ISSUE TITLE
About the MPI-Sintel datasets

### ISSUE THREAD

**Issue by PkuRainBow** [NVIDIA/flownet2-pytorch#11]
In your command:

```
# Example on MPISintel Final and Clean, with MultiScale loss on FlowNet2C model 
python main.py --batch_size 8 --model FlowNet2C --optimizer=Adam --optimizer_lr=1e-4 --loss=MultiScale --loss_norm=L1 \
--loss_numScales=5 --loss_startScale=4 --optimizer_lr=1e-4 --crop_size 384 512 \
--training_dataset FlyingChairs --training_dataset_root /path/to/flying-chairs/dataset  \
--validation_dataset MpiSintelClean --validation_dataset_root /path/to/mpi-sintel/clean/dataset
```

We need to pass the path of the MPI-Sintel datasets. So I use the absolute path to the clean folder under the train folder. But the image files and flow files are arranged separately.

Here the original folder tree of MPI-Sintel datasets, so I am wondering do I need to rearrange the files as the images and flo files are arranged seperately while your code seems can not deal with the original tree structure. So how should I change this?

![image](https://user-images.githubusercontent.com/4639578/34283820-f2aad87e-e708-11e7-95c5-0154f2189e37.png)

**Comment by fitsumreda** [comment]
@PkuRainBow You can replace the `validation_*` with either `clean` or `final` as below:

--validation_dataset MpiSintelClean \
--validation_dataset_root ./MPI-Sintel/training

or 
--validation_dataset MpiSintelFinal 
--validation_dataset_root ./MPI-Sintel/training

Both should work fine.

**Comment by PkuRainBow** [comment]
@fitsumreda Thanks for your quick reply. I find there exist 2 small bugs on the line 318 - 319 of the main.py

```
                    logger.add_scalar('average batch ' + key, all_losses[:, i].mean(), global_iteration)
                    logger.add_histogram(key, all_losses[:, i], global_iteration)
```

should be modified to 

```
                    logger.add_scalar('average batch ' + str(key), all_losses[:, i].mean(), global_iteration)
                    logger.add_histogram(str(key), all_losses[:, i], global_iteration)
```

**Comment by PkuRainBow** [comment]
@fitsumreda Besides, I am wondering when it would be possible for you to share the evaluation and visualization codes for the flow datasets. Besides, when can we have access to your well trained models as I find that it takes 10000 epochs and each epoch takes my TITAN for 1-2 hours, which is super time consuming!!!

**Comment by PkuRainBow** [comment]
@fitsumreda Could you share me advice on how to accelerate the training procedures? e.g., Is the hard drive the main problem? Changing it to SSD could accelerate?

**Comment by fitsumreda** [comment]
we'll address this issue with the Performance issue that is still open.

**Comment by flyingmoth** [comment]
@PkuRainBow I can't download the MPI-Sintel flow datasets.   Could you share the MPI-Sintel flow datasets by google dirve or baidu drive?

**Comment by fitsumreda** [comment]
i'm not able to reproduce this error.

**Comment by tjusxh** [comment]
@kaixu93 @PkuRainBow  I also don't download the flow dataset.(http://sintel.is.tue.mpg.de/downloads )  How do you download the Mpi-Sintel?

My download dataset struct as following,
![image](https://user-images.githubusercontent.com/9691664/58009572-56171000-7b21-11e9-8a9c-15ac009bf6d4.png)

**Comment by tjusxh** [comment]
I download the dataset contains flow dataset from http://sintel.is.tue.mpg.de/downloads Complete Dataset. Others links don't contain flow dataset.

**Comment by lesurp** [comment]
Hi, sorry to ask this here, but I cannot find the MPI-Sintel dataset anywhere. It seems it's not on their webpage any more (the link given above 404). Is there any other place one could download this?
