### ISSUE TITLE
ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by oee5215** [NVIDIA/flownet2-pytorch#119]
Hi,

I've been trying to test the Flownet2 model on inference mode, but I keep running into this error. It seems to be an error from python itself, since the traceback does not reference any function within this program. Is anybody else having the same issue?

<img width="932" alt="capture d ecran 2019-01-02 a 15 12 10" src="https://user-images.githubusercontent.com/43939700/51205047-060a1180-18d3-11e9-94d0-54bd76e70c31.png">

**Comment by oee5215** [comment]
Fixed after updating to python 3.7 and implementing the fix in #104 for the async keyword.

**Comment by ssafar** [comment]
... for anyone who is also running into this: the "signal number 32 out of range" part is a Python bug & it's been fixed as of 3.6.6 or 3.5.7... in case you can't go all the way to 3.7 (see [this stackoverflow post](https://stackoverflow.com/questions/53300965/pytorch-exception-in-thread-valueerror-signal-number-32-out-of-range/58861719#58861719) for more details).
