### ISSUE TITLE
Inference with FlowNetC model

### ISSUE THREAD

**Issue by PkuRainBow** [NVIDIA/flownet2-pytorch#12]
Hi, I have trained the FlowNet2C model and want to test it but I meet the following errors.

Here is the command I am excuting.

```
python main.py --inference --model FlowNet2C --save_flow --inference_dataset MpiSintelClean \
--inference_dataset_root /path/to/mpi-sintel/clean/dataset \
--resume /path/to/checkpoints 
```

Could you help me?

![default](https://user-images.githubusercontent.com/4639578/34331717-344bfe40-e964-11e7-9ae0-5780a1eff92f.png)

**Comment by fitsumreda** [comment]
Hi @PkuRainBow , 
Thanks for catching this, it is a bug.
Line 357 in 'main.py` , `_pflow[i]` should be `_pflow'.
should work now.

**Comment by PkuRainBow** [comment]
@fitsumreda  Thanks!
