### ISSUE TITLE
CUDA error when apply large kernel size

### ISSUE THREAD

**Issue by Lanselott** [NVIDIA/flownet2-pytorch#128]
I'm trying to apply large kernel  size on correlation, 

But, I got this **error**:

File "/research/byu2/rchen/proj/flownet2-pytorch/networks/correlation_packa
ge/correlation.py", line 59, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_di
splacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
  File "/research/byu2/rchen/proj/flownet2-pytorch/networks/correlation_packa
ge/correlation.py", line 27, in forward
    self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self
.stride2, self.corr_multiply)
RuntimeError: CUDA call failed (correlation_forward_cuda at correlation_cuda.
cc:82)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (
0x7f0d70b01cc5 in /research/byu2/rchen/anaconda2/envs/correlation/lib/python3
.7/site-packages/torch/lib/libc10.so)
frame #1: correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at:
:Tensor&, at::Tensor&, int, int, int, int, int, int) + 0x6c4 (0x7f0d5001cc54
in /research/byu2/rchen/anaconda2/envs/correlation/lib/python3.7/site-package
s/correlation_cuda-0.0.0-py3.7-linux-x86_64.egg/correlation_cuda.cpython-37m-
x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x178b9 (0x7f0d500288b9 in /research/byu2/rche
n/anaconda2/envs/correlation/lib/python3.7/site-packages/correlation_cuda-0.0
.0-py3.7-linux-x86_64.egg/correlation_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x17a8e (0x7f0d50028a8e in /research/byu2/rche
n/anaconda2/envs/correlation/lib/python3.7/site-packages/correlation_cuda-0.0
.0-py3.7-linux-x86_64.egg/correlation_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x14725 (0x7f0d50025725 in /research/byu2/rche
n/anaconda2/envs/correlation/lib/python3.7/site-packages/correlation_cuda-0.0
.0-py3.7-linux-x86_64.egg/correlation_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_do_forward(THPFunction*, _object*) + 0x15c (0x7f0da0f9
b33c in /research/byu2/rchen/anaconda2/envs/correlation/lib/python3.7/site-pa
ckages/torch/lib/libtorch_python.so)
frame #54: __libc_start_main + 0xf5 (0x7f0db97c4445 in /lib64/libc.so.6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pytorch/train_check_baseline_8.py", line 801, in <module>
    fire.Fire()
  File "/uac/gds/rchen/.local/lib/python3.7/site-packages/fire/core.py", line
 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/uac/gds/rchen/.local/lib/python3.7/site-packages/fire/core.py", line
 366, in _Fire
    component, remaining_args)
  File "/uac/gds/rchen/.local/lib/python3.7/site-packages/fire/core.py", line
 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "./pytorch/train_check_baseline_8.py", line 547, in train
    net.get_global_step())
  File "/research/byu2/rchen/proj/second.pytorch/second/pytorch/models/voxeln
et13.py", line 725, in get_global_step
    return int(self.global_step.cpu().numpy()[0])
RuntimeError: CUDA error: an illegal memory access was encountered

The correlation works fine when I set it as:
        self.corr = Correlation(pad_size=15, kernel_size=4, max_displacement=14, stride1=1, stride2=3)
or    self.corr = Correlation(pad_size=16, kernel_size=5, max_displacement=14, stride1=1, stride2=3)

it got error, when I set as:
For example:
        self.corr_test = Correlation(pad_size=16, kernel_size=7, max_displacement=14, stride1=1, stride2=3)        
    
Any idea?

**Comment by Lanselott** [comment]
I found out that, this error only happens on Titan V, it works fine on 1080Ti. Maybe it's some like a cuda version error.

**Comment by huangbiubiu** [comment]
In my case, this error happens in CPU mode. Passing CUDA tensors to corrlation module fix the problem.

**Comment by EthanZhangYi** [comment]
Please refer to #167
