### ISSUE TITLE
Bash install.sh ERROR,Ubuntu16.04LTS, Anaconda2 python2.7 

### ISSUE THREAD

**Issue by yyf8989** [NVIDIA/flownet2-pytorch#130]
Envs:
Ubuntu:Ubuntu16.04LTS
Python:Python2.7
Anaconda:Anaconda2
Others: Pytorch 1.0.0_dev2019(included caffe2)
             Densepose installed 

(densepose) yyf@yyf:~/PycharmProjects/vid2vid/models/flownet2_pytorch$ bash install.sh 
running install
running bdist_egg
running egg_info
writing correlation_cuda.egg-info/PKG-INFO
writing top-level names to correlation_cuda.egg-info/top_level.txt
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'correlation_cuda' extension
gcc -pthread -B /home/yyf/anaconda2/envs/densepose/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/TH -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyf/anaconda2/envs/densepose/include/python2.7 -c correlation_cuda.cc -o build/temp.linux-x86_64-2.7/correlation_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from correlation_cuda.cc:1:0:
/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
correlation_cuda.cc: In function ‘int correlation_forward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int)’:
correlation_cuda.cc:74:25: error: ‘class at::Context’ has no member named ‘getCurrentCUDAStream’
     at::globalContext().getCurrentCUDAStream()
                         ^
correlation_cuda.cc: In function ‘int correlation_backward_cuda(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, int, int, int, int, int, int)’:
correlation_cuda.cc:155:69: error: ‘class at::Context’ has no member named ‘getCurrentCUDAStream’
                                                 at::globalContext().getCurrentCUDAStream()
                                                                     ^
error: command 'gcc' failed with exit status 1
running install
running bdist_egg
running egg_info
writing resample2d_cuda.egg-info/PKG-INFO
writing top-level names to resample2d_cuda.egg-info/top_level.txt
writing dependency_links to resample2d_cuda.egg-info/dependency_links.txt
reading manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'resample2d_cuda' extension
gcc -pthread -B /home/yyf/anaconda2/envs/densepose/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/TH -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyf/anaconda2/envs/densepose/include/python2.7 -c resample2d_cuda.cc -o build/temp.linux-x86_64-2.7/resample2d_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from resample2d_cuda.cc:2:0:
/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/local/cuda/bin/nvcc -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/TH -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyf/anaconda2/envs/densepose/include/python2.7 -c resample2d_kernel.cu -o build/temp.linux-x86_64-2.7/resample2d_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
resample2d_kernel.cu(211): error: class "at::Context" has no member "getCurrentCUDAStream"

resample2d_kernel.cu(256): error: class "at::Context" has no member "getCurrentCUDAStream"

resample2d_kernel.cu(283): error: class "at::Context" has no member "getCurrentCUDAStream"

3 errors detected in the compilation of "/tmp/tmpxft_000074a1_00000000-10_resample2d_kernel.compute_70.cpp1.ii".
error: command u'/usr/local/cuda/bin/nvcc' failed with exit status 1
running install
running bdist_egg
running egg_info
writing channelnorm_cuda.egg-info/PKG-INFO
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'channelnorm_cuda' extension
gcc -pthread -B /home/yyf/anaconda2/envs/densepose/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/TH -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyf/anaconda2/envs/densepose/include/python2.7 -c channelnorm_cuda.cc -o build/temp.linux-x86_64-2.7/channelnorm_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from channelnorm_cuda.cc:1:0:
/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/local/cuda/bin/nvcc -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/TH -I/home/yyf/anaconda2/envs/densepose/lib/python2.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyf/anaconda2/envs/densepose/include/python2.7 -c channelnorm_kernel.cu -o build/temp.linux-x86_64-2.7/channelnorm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
channelnorm_kernel.cu(110): error: class "at::Context" has no member "getCurrentCUDAStream"

channelnorm_kernel.cu(110): error: class "at::Context" has no member "getCurrentCUDAStream"

channelnorm_kernel.cu(110): error: class "at::Context" has no member "getCurrentCUDAStream"

channelnorm_kernel.cu(150): error: class "at::Context" has no member "getCurrentCUDAStream"

channelnorm_kernel.cu(150): error: class "at::Context" has no member "getCurrentCUDAStream"

channelnorm_kernel.cu(150): error: class "at::Context" has no member "getCurrentCUDAStream"

6 errors detected in the compilation of "/tmp/tmpxft_00007a6d_00000000-9_channelnorm_kernel.compute_70.cpp1.ii".
error: command u'/usr/local/cuda/bin/nvcc' failed with exit status 1

Is there anybody can help me figure out this problem?

**Comment by yyf8989** [comment]
I found out that warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h",this means I change envs for torch/extension.h? but i don't know how change this~

**Comment by yyf8989** [comment]
also this issue :cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++, what can i do for this?

**Comment by TomHeaven** [comment]
Its turns out that we have to update three files networks/correlation_package/correlation_cuda.cc, networks/resample2d_package/resample2d_kernel.cu and /network/channelnorm_package/channelnorm_kernel.cu by

adding #include <ATen/cuda/CUDAContext.h> at top
replacing all at::globalContext().getCurrentCUDAStream() with at::cuda::getCurrentCUDAStream()
Optionally, replace #include <torch/torch.h> by #include <torch/extension.h> .
Then, the custom layers should be compiled.

I met the same problem, see https://github.com/NVIDIA/flownet2-pytorch/issues/131.

**Comment by yyf8989** [comment]
> Its turns out that we have to update three files `networks/correlation_package/correlation_cuda.cc`, `networks/resample2d_package/resample2d_kernel.cu` and `/network/channelnorm_package/channelnorm_kernel.cu` by
> 
>     1. adding `#include <ATen/cuda/CUDAContext.h>` at top
> 
>     2. replacing all `at::globalContext().getCurrentCUDAStream()` with `at::cuda::getCurrentCUDAStream()`
> 
>     3. Optionally, replace `#include <torch/torch.h> ` by `#include <torch/extension.h> `.
> 
> 
> Then, the custom layers should be compiled.
> 
> I met the same problem, see #131.

tks very much, it worked after i followed you advise!! HAHAHA

**Comment by alfassy** [comment]
> Its turns out that we have to update three files `networks/correlation_package/correlation_cuda.cc`, `networks/resample2d_package/resample2d_kernel.cu` and `/network/channelnorm_package/channelnorm_kernel.cu` by
> 
> 1. adding `#include <ATen/cuda/CUDAContext.h>` at top
> 2. replacing all `at::globalContext().getCurrentCUDAStream()` with `at::cuda::getCurrentCUDAStream()`
> 3. Optionally, replace `#include <torch/torch.h> ` by `#include <torch/extension.h> `.
> 
> Then, the custom layers should be compiled.
> 
> I met the same problem, see #131.

Hi,

The problem persist for me, even after editing those files.
I also tried creating a fresh environment, installing the dependencies and try again, no luck.
Do you have an idea what could be the problem?
Thx!
Amit

**Comment by yyf8989** [comment]
> > Its turns out that we have to update three files `networks/correlation_package/correlation_cuda.cc`, `networks/resample2d_package/resample2d_kernel.cu` and `/network/channelnorm_package/channelnorm_kernel.cu` by
> > 
> > 1. adding `#include <ATen/cuda/CUDAContext.h>` at top
> > 2. replacing all `at::globalContext().getCurrentCUDAStream()` with `at::cuda::getCurrentCUDAStream()`
> > 3. Optionally, replace `#include <torch/torch.h> ` by `#include <torch/extension.h> `.
> > 
> > Then, the custom layers should be compiled.
> > I met the same problem, see #131.
> 
> Hi,
> 
> The problem persist for me, even after editing those files.
> I also tried creating a fresh environment, installing the dependencies and try again, no luck.
> Do you have an idea what could be the problem?
> Thx!
> Amit

please show your error log here (not necessary if your log  same as me ),then it can be read by everyone who maybe help u solve your problem
