### ISSUE TITLE
Asking support for Pytorch 1.0

### ISSUE THREAD

**Issue by TomHeaven** [NVIDIA/flownet2-pytorch#131]
When I run the code using Pytorch 1.0 (cuda 10), it reported error about not finding:
```
at::globalContext().getCurrentCUDAStream() 
```
in source.

As pytorch 1.0 stable release has been released for months, it may be the proper time to move the project foward.

**Comment by TomHeaven** [comment]
Its turns out that we have to update three files `networks/correlation_package/correlation_cuda.cc`, `networks/resample2d_package/resample2d_kernel.cu` and `/network/channelnorm_package/channelnorm_kernel.cu` by

1.  adding `#include <ATen/cuda/CUDAContext.h>` at top
2. replacing all `at::globalContext().getCurrentCUDAStream()` with `at::cuda::getCurrentCUDAStream()`
3. Optionally, replace `#include <torch/torch.h> ` by `#include <torch/extension.h> `.

Then, the custom layers should be compiled.

**Comment by ming-c** [comment]
Hi @TomHeaven ,

I could manage to compile the custom layers with your solution using pytorch 1.0.1. Thanks for that.

But when I run the forward of the network, an segmentation error occurred and it seems to be an issue with this line https://github.com/NVIDIA/flownet2-pytorch/blob/2787b3a920416a3d62133b5c07f0efaebd6ba3c3/networks/correlation_package/correlation.py#L26 forward.
Have you seen the same issue?

Cheers.

**Comment by TomHeaven** [comment]
I always encounter a segmentation fault when the program exit. The function completes normally. So maybe it's a different issue.

**Comment by bomb2peng** [comment]
Hi, @ming-c , I have the same error using pytorch 1.1.0, cuda 10.1. Did you solve this segmentation error problem?

**Comment by 1179021477** [comment]
i also have this problem, how can you solve it?

**Comment by Zealoe** [comment]
So have you solved this problem? Thanks. 
@TomHeaven @bomb2peng @ming-c @1179021477

**Comment by hsyi** [comment]
Have you solved this Segmentaion Fault?
@TomHeaven @bomb2peng @ming-c @1179021477 @Zealoe

**Comment by yanwenCi** [comment]
> Hi @TomHeaven ,
> 
> I could manage to compile the custom layers with your solution using pytorch 1.0.1. Thanks for that.
> 
> But when I run the forward of the network, an segmentation fault occurred and it seems to be an issue with this line
> 
> https://github.com/NVIDIA/flownet2-pytorch/blob/2787b3a920416a3d62133b5c07f0efaebd6ba3c3/networks/correlation_package/correlation.py#L26
> 
> forward.
> Have you seen the same issue?
> I am using ubuntu 14.04, cuda-9.0, gcc-4.9, pytorch 1.0.1
> 
> Cheers.

I  have the same error. did you figure it out? Thanks

**Comment by mailvijayasingh** [comment]
@yanwenCi 
Were you able to solve this? I get the same error
