### ISSUE TITLE
resample2d_cuda.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by yyf8989** [NVIDIA/flownet2-pytorch#136]
import resample2d_cuda
  File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 6, in __bootstrap__
ImportError: /home/yyf/.cache/Python-Eggs/resample2d_cuda-0.0.0-py2.7-linux-x86_64.egg-tmp/resample2d_cuda.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

what's the problem?
my envs.
sys: Centos 7
protobuf ==3.5.0
pytorch = 1.0.1
gcc = 4.9.2

what's the UndefinedTensorLmpl10....
 I found my path  is in###  _**.cache/**_ when i saw someone's path is in .local/
how  did this happened?
is there someone can help me?

**Comment by yyf8989** [comment]
> import resample2d_cuda
> File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 7, in
> File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 6, in **bootstrap**
> ImportError: /home/yyf/.cache/Python-Eggs/resample2d_cuda-0.0.0-py2.7-linux-x86_64.egg-tmp/resample2d_cuda.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
> 
> what's the problem?
> my envs.
> sys: Centos 7
> protobuf ==3.5.0
> pytorch = 1.0.1
> gcc = 4.9.2
> 
> what's the UndefinedTensorLmpl10....
> I found my path is in### _**.cache/**_ when i saw someone's path is in .local/
> how did this happened?
> is there someone can help me?

I also saw answers ( pytorch version problem), but i don't think so, is there other advice?

**Comment by yyf8989** [comment]
> > import resample2d_cuda
> > File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 7, in
> > File "build/bdist.linux-x86_64/egg/resample2d_cuda.py", line 6, in **bootstrap**
> > ImportError: /home/yyf/.cache/Python-Eggs/resample2d_cuda-0.0.0-py2.7-linux-x86_64.egg-tmp/resample2d_cuda.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
> > what's the problem?
> > my envs.
> > sys: Centos 7
> > protobuf ==3.5.0
> > pytorch = 1.0.1
> > gcc = 4.9.2
> > what's the UndefinedTensorLmpl10....
> > I found my path is in### _**.cache/**_ when i saw someone's path is in .local/
> > how did this happened?
> > is there someone can help me?
> 
> I also saw answers ( pytorch version problem), but i don't think so, is there other advice?

I found that this was a torch compiled version too

**Comment by oysz2016** [comment]
I had the same problem，Have you solved it？

**Comment by yyf8989** [comment]
> I had the same problem，Have you solved it？

yes， this was pytorch‘s version problem, you should change some files
[https://github.com/NVIDIA/flownet2-pytorch/issues/130](url)

Optionally, replace #include <torch/torch.h> by #include <torch/extension.h> 
this is about your torch version, you can change this include for building flownet

**Comment by mayujie** [comment]
- nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
- gcc-7 g++-7
- python3.6
- pip3
- `pip3 install torch==1.0.0 -f https://download.pytorch.org/whl/cu90/torch_stable.html`

works for me! :)
