### ISSUE TITLE
Any natural methods to implement 1D Correlation layer with your 2D correlation

### ISSUE THREAD

**Issue by blackjack201312** [NVIDIA/flownet2-pytorch#14]
Hi. This is really a wonderful work. I'd know if there is any easy way to implement 1D Correlation layer with your 2D Correlation. Thank you!

**Comment by fitsumreda** [comment]
Hi @blackjack201312 if you are looking to do a Correlation over 2D feature-maps wth a `kernel_size=1x1`, then the default arguments to this implementation are actually `kernel_size=1x1` and `displacement_radius=20`, with a `stride=1` for the first feature map and a `stride=2` for the second.

If you are looking for a Correlation operation over 1D feature maps, then it is not trivial to adapt this package for your purpose.
