### ISSUE TITLE
poor result , look at this.

### ISSUE THREAD

**Issue by EthanGuan** [NVIDIA/flownet2-pytorch#148]
I run inference on my own dataset, it gives me this result, however, EpicFlow gives good result.
![a](https://user-images.githubusercontent.com/18432344/57686510-4c4a6400-766c-11e9-9f86-3145b92b69df.png)

**Comment by hjzh4** [comment]
Hi Ethan, 

I got similar result with this, how do you solve the problem? Thansk!
