### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by MQZhang2014** [NVIDIA/flownet2-pytorch#188]
when I ran "main.py", I met the problem like this:
  File "/media/HardDisk_A/zmq/flownet2-pytorch/models.py", line 9, in <module>
    from networks.resample2d_package.resample2d import Resample2d
  File "/media/HardDisk_A/zmq/flownet2-pytorch/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: /home/zmq/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "/media/HardDisk_A/zmq/flownet2-pytorch/models.py", line 19, in <module>
    from .networks.resample2d_package.resample2d import Resample2d
ImportError: attempted relative import with no known parent package

**Comment by LiUzHiAn** [comment]
Hi, @MQZhang2014 
Don't forget to run `install.sh` to support custom layers in advance. 

In my case, I just used the `FlowNet2SD` model, so I commented out the `import channelnorm_cuda` in `network/channelnorm_package` and solutions are the same in other similar packages.

**Comment by MQZhang2014** [comment]
Thank you for your reply. It turns out that your "comment out" method is really amazing. It did work. @LiUzHiAn
