### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by buliginleo** [NVIDIA/flownet2-pytorch#2]
Hello!

Thank for your great implementation!

Can you publish pretrained models please if it's possible?

**Comment by JoeHEZHAO** [comment]
I need one too. Please upload if available. Thanks !

**Comment by qijiezhao** [comment]
+1...
hope the official repo could release soon

**Comment by fitsumreda** [comment]
we'll release scripts that downloads and converts flownet2-official (from authors) Caffe pre-trained models to PyTorch, which can be used with `--resume` argument in this repository
we will provide information about model training from scratch.

**Comment by fitsumreda** [comment]
we've added instructions that downloads and converts official caffe-pre-trained models to PyTorch.
you may use the converted checkpoints with the `--resume` argument in this repository
