### ISSUE TITLE
error "nvcc fatal : Unsupported gpu architecture 'compute_60'"

### ISSUE THREAD

**Issue by vidit98** [NVIDIA/flownet2-pytorch#205]
Did anybody was able to run the installation with the following specs:
torch - 1.1.0
CUDA - 10.1
cuDNN - 7.5.17
python 3.5
GPU - RTX2080
ubuntu - 16.04

The error is given below:

running install
running bdist_egg
running egg_info
creating correlation_cuda.egg-info
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
writing top-level names to correlation_cuda.egg-info/top_level.txt
writing correlation_cuda.egg-info/PKG-INFO
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'correlation_cuda' extension
creating build
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c correlation_cuda.cc -o build/temp.linux-x86_64-3.5/correlation_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from correlation_cuda.cc:1:0:
/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/bin/nvcc -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c correlation_cuda_kernel.cu -o build/temp.linux-x86_64-3.5/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=correlation_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc fatal   : Unsupported gpu architecture 'compute_60'
error: command '/usr/bin/nvcc' failed with exit status 1
running install
running bdist_egg
running egg_info
creating resample2d_cuda.egg-info
writing top-level names to resample2d_cuda.egg-info/top_level.txt
writing resample2d_cuda.egg-info/PKG-INFO
writing dependency_links to resample2d_cuda.egg-info/dependency_links.txt
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
reading manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'resample2d_cuda' extension
creating build
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c resample2d_cuda.cc -o build/temp.linux-x86_64-3.5/resample2d_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from resample2d_cuda.cc:2:0:
/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/bin/nvcc -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c resample2d_kernel.cu -o build/temp.linux-x86_64-3.5/resample2d_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc fatal   : Unsupported gpu architecture 'compute_60'
error: command '/usr/bin/nvcc' failed with exit status 1
running install
running bdist_egg
running egg_info
creating channelnorm_cuda.egg-info
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
writing channelnorm_cuda.egg-info/PKG-INFO
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'channelnorm_cuda' extension
creating build
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c channelnorm_cuda.cc -o build/temp.linux-x86_64-3.5/channelnorm_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from channelnorm_cuda.cc:1:0:
/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
/usr/bin/nvcc -I/home/ark/.local/lib/python3.5/site-packages/torch/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/torch/csrc/api/include -I/home/ark/.local/lib/python3.5/site-packages/torch/include/TH -I/home/ark/.local/lib/python3.5/site-packages/torch/include/THC -I/usr/include/python3.5m -c channelnorm_kernel.cu -o build/temp.linux-x86_64-3.5/channelnorm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc fatal   : Unsupported gpu architecture 'compute_60'
error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by ivineetm007** [comment]
Hi,
I am facing the same issue. I am installing flownet in conda environment. It shows -
"nvcc fatal   : Unsupported gpu architecture ' compute_61'
error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1"

Based on other issues, I have tried different versions of both cuda 9 and 10 with pytorch 0.4,0.41 and 1.0 in the conda environment.
How did you solve it?

Thanks in advance
