### ISSUE TITLE
NaN or Inf found in input tensor and strange values appear on the loss

### ISSUE THREAD

**Issue by leehr1227** [NVIDIA/flownet2-pytorch#206]
Hi. thanks for your code.I got a strange error, using command:
python3 -W ignore \
    main.py \
    --batch_size 16 \
    --model FlowNet2 \
    --loss=L1Loss \
    --optimizer=Adam \
    --optimizer_lr=1e-4 \
    --training_dataset FlyingChairs \
    --training_dataset_root ~/hdd_data/flyingchairs/FlyingChairs_release/data \
    --validation_dataset FlyingChairs \
    --validation_dataset_root ~/hdd_data/flyingchairs/FlyingChairs_release/val

Program runs on ubuntu18.04 with python3.6.9 and pytorch1.4.0
Note the L1loss at epoch6.

Program output:
Validating Epoch 0 L1: 9.678, EPE: 15.201, load: 0.012: 100%|█████| 40/40.0 [00:20<00:00,  1.99it/s]
Saving Checkpoint: 1it [00:03,  3.85s/it], load: 0.012: 100%|█████| 40/40.0 [00:20<00:00,  1.79it/s]
Training Epoch 1 L1: 5.335, EPE: 8.314, lr: 1.0e-04, load: 2.9e-05: 100%|█████████| 1389/1389.0 [24:04<00:00,  1.04s/it]
Saving Checkpoint: 1it [00:00,  1.52it/s]
Validating Epoch 1 L1: 9.135, EPE: 14.030, load: 0.013: 100%|█████| 40/40.0 [00:28<00:00,  1.39it/s]
Saving Checkpoint: 1it [00:03,  3.65s/it]r: 1.0e-04, load: 2.9e-05: 100%|█████████| 1389/1389.0 [24:04<00:00,  1.03it/s]
Training Epoch 2 L1: 11.609, EPE: 18.130, lr: 1.0e-04, load: 3.1e-05: 100%|███████| 1389/1389.0 [22:19<00:00,  1.04it/s]
Saving Checkpoint: 1it [00:01,  1.88s/it]
Validating Epoch 2 L1: 13.614, EPE: 21.379, load: 0.014: 100%|████| 40/40.0 [00:27<00:00,  1.46it/s]
Saving Checkpoint: 1it [00:01,  1.89s/it]
Training Epoch 3 L1: 5.876, EPE: 9.391, lr: 1.0e-04, load: 3.0e-05: 100%|█████████| 1389/1389.0 [22:22<00:00,  1.03it/s]
Saving Checkpoint: 1it [00:01,  1.90s/it]
Validating Epoch 3 L1: 8.706, EPE: 13.470, load: 1.6e-05: 100%|███| 40/40.0 [00:27<00:00,  1.47it/s]19<00:00,  1.04it/s]
Saving Checkpoint: 1it [00:01,  1.93s/it]
Training Epoch 4 L1: 8.763, EPE: 13.411, lr: 1.0e-04, load: 0.616: 100%|██████████| 1389/1389.0 [25:54<00:00,  1.12s/it]
Saving Checkpoint: 1it [00:01,  1.94s/it]9, load: 0.014: 100%|████| 40/40.0 [00:27<00:00,  1.84it/s]
Validating Epoch 4 L1: 9.355, EPE: 14.317, load: 0.416: 100%|█████| 40/40.0 [00:43<00:00,  1.09s/it]
Saving Checkpoint: 1it [00:03,  3.65s/it]
Training Epoch 5 L1: 5.781, EPE: 8.915, lr: 1.0e-04, load: 0.316: 100%|███████████| 1389/1389.0 [24:37<00:00,  1.06s/it]
Saving Checkpoint: 1it [00:01,  1.92s/it]r: 1.0e-04, load: 3.0e-05: 100%|█████████| 1389/1389.0 [22:22<00:00,  1.04it/s]
Validating Epoch 5 L1: 9.758, EPE: 15.138, load: 1.6e-05: 100%|███| 40/40.0 [00:43<00:00,  1.08s/it]
Saving Checkpoint: 1it [00:01,  1.88s/it]
Training Epoch 6 L1: 16898570.000, EPE: 26836056.000, lr: 1.0e-04, load: 0.525: 100%|█| 1389/1389.0 [24:52<00:00,  1.07s
Saving Checkpoint: 1it [00:01,  1.93s/it]
Validating Epoch 6 L1: 15703730.000, EPE: 24894882.000, load: 0.725: 100%|█| 40/40.0 [00:43<00:00,  
Saving Checkpoint: 1it [00:01,  1.90s/it]
Training Epoch 7 L1: 8260385.000, EPE: 13293490.000, lr: 1.0e-04, load: 1.903: 100%|█| 1389/1389.0 [24:38<00:00,  1.06s/
Saving Checkpoint: 1it [00:01,  1.89s/it]
Validating Epoch 7 L1: 8048915.000, EPE: 12950434.000, load: 1.6e-05: 100%|█| 40/40.0 [00:43<00:00, 
Saving Checkpoint: 1it [00:01,  1.88s/it], load: 0.416: 100%|█████| 40/40.0 [00:43<00:00,  1.06s/it]
Training Epoch 8 L1: 63609960.000, EPE: 101154360.000, lr: 1.0e-04, load: 1.5e-05: 100%|█| 1389/1389.0 [24:16<00:00,  1.
Saving Checkpoint: 1it [00:01,  1.89s/it]
Validating Epoch 8 L1: 67441792.000, EPE: 107078640.000, load: 1.6e-05: 100%|█| 40/40.0 [00:43<00:00
Saving Checkpoint: 1it [00:01,  1.94s/it]r: 1.0e-04, load: 0.316: 100%|███████████| 1389/1389.0 [24:37<00:00,  1.24s/it]
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
Traceback (most recent call last): 
  File "main.py", line 426, in <module>
    train_loss, iterations = train(args=args, epoch=epoch, start_iteration=global_iteration, data_loader=train_loader, model=model_and_loss, optimizer=optimizer, logger=train_logger, offset=offset)
  File "main.py", line 325, in train
    logger.add_histogram(str(key), all_losses[:, i], global_iteration)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 496, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 200, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 238, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.').

**Comment by Nestart** [comment]
hi! i run into the same problem as you did. could you tell me how to fix this? thanks.

**Comment by WangZhen1175701153** [comment]
> hi! i run into the same problem as you did. could you tell me how to fix this? thanks.

hello, I had the same problem. Have you solved it? I think the problem might come from the validation set or the loss function.

**Comment by xianpf** [comment]
> > hi! i run into the same problem as you did. could you tell me how to fix this? thanks.
> 
> hello, I had the same problem. Have you solved it? I think the problem might come from the validation set or the loss function.

Hi, I got thee same problem, do you have any idea to address this problem?

**Comment by luanyue-ly** [comment]
Hi, I got thee same problem, do you have any idea to address this problem?
