### ISSUE TITLE
torch.FatalError: aborting at correlation_cuda.c

### ISSUE THREAD

**Issue by PkuRainBow** [NVIDIA/flownet2-pytorch#21]
Could anyone help me with this problem?

![image](https://user-images.githubusercontent.com/4639578/34525674-c096405e-f0da-11e7-9275-b562a525cd27.png)

**Comment by fitsumreda** [comment]
It'd help to debug this if you share the input arguments you used for this run

**Comment by PkuRainBow** [comment]
@fitsumreda 

![image](https://user-images.githubusercontent.com/4639578/34551426-bbea98d2-f154-11e7-9fdc-147b65c14a8a.png)

**Comment by fitsumreda** [comment]
i'm not able to reproduce this error.

**Comment by xianyuhong** [comment]
I am getting the same error too.
