### ISSUE TITLE
How to get horizontal and vertical optical flow?

### ISSUE THREAD

**Issue by 1187697147** [NVIDIA/flownet2-pytorch#221]
Hi, 
To reproduction one paper, i need to use optical flow. However, that paper uses horizontal and vertical optical flow(X-Y)  rather than one optical flow, my question is that can FlowNet2 supports to get horizontal and vertical optical flow?
Thanks.

**Comment by albertchristian92** [comment]
Hi @1187697147 did you solve how to find horizontal and vertical optical flow? 

Thank you

**Comment by 1187697147** [comment]
Find the line that saves the flo file in main.py
There is an intermediate variable in the upper line of save flo, you can split that variable into two directions and save it.
