### ISSUE TITLE
ModuleNotFoundError: No module named 'networks'

### ISSUE THREAD

**Issue by TheRustlessSummer** [NVIDIA/flownet2-pytorch#236]
Hello , when I run the code of consistent_depth which use flownet2 as a third party , there are some errors .
`ModuleNotFoundError: No module named 'networks'`
`ModuleNotFoundError: No module named 'third_party.flownet2.networks.resample2d_package'`
![图片](https://user-images.githubusercontent.com/48950800/96062271-d8973100-0ec7-11eb-815e-582e1f276878.png)

- [ubuntu-18.04 ] 

- [python-3.6 ] 

- [cuda-10.0 ] 

- [pytorch-1.4.0 ]

**Comment by TheRustlessSummer** [comment]
I have changed this , cause there is no resample2d_package in my folder networks. I git down the resample2d_package from flownet2-pytorch and copy it into folder , the question has been solved.

**Comment by panhuixiao1999** [comment]
l meet the same problem,i try a lots of way,but can't solve,how to solve it?
