### ISSUE TITLE
Should convert the input image from RGB to BGR?

### ISSUE THREAD

**Issue by flyingmoth** [NVIDIA/flownet2-pytorch#24]
The official Caffe version implementation converts it.
`img0 = misc.imread(args.img0)
if len(img0.shape) < 3: input_data.append(img0[np.newaxis, np.newaxis, :, :])
else:                   input_data.append(img0[np.newaxis, :, :, :].transpose(0, 3, 1, 2)[:, [2, 1, 0], :, :])`
But this pytorch implementation doesn't.

**Comment by fitsumreda** [comment]
the converted pre-trained models/checkpoints already reflect this RGB to BGR conversion. 

If you train from scratch, then this conversion is not relevant.
