### ISSUE TITLE
NameError: name 'inference_loader' is not defined

### ISSUE THREAD

**Issue by slokaanugu** [NVIDIA/flownet2-pytorch#250]
Hi, 

I am getting NameError: name 'inference_loader' is not defined error.

I am running the below command:

python3 main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /home/user/sp/prediction/flownet2-pytorch/mpi-sintel/clean --resume checkpoint/FlowNet2_checkpoint.pth.tar

The folder structure of my mpi-sintel is as follows:

mpi-sintel
    -clean
         1.bundler
         2. test
             2a. final
             2b. clean
         3.flow_code

Where Am I going wrong? For the inference_dataset_root  argument, I tried giving the below paths but all are giving the same error:
1./home/user/sp/prediction/flownet2-pytorch/mpi-sintel/clean/test
2. /home/user/sp/prediction/flownet2-pytorch/mpi-sintel/clean/final
3. /home/user/sp/prediction/flownet2-pytorch/mpi-sintel/clean/final/wall

**Comment by izhimahu** [comment]
I have the same problem. Have you solved it?
