### ISSUE TITLE
Inconsistent tensor sizes

### ISSUE THREAD

**Issue by flyingmoth** [NVIDIA/flownet2-pytorch#27]
There is a bug when the input image size is not  2 to the n.  

> concat4 = torch.cat((out_conv4,out_deconv4,flow5_up),1)

> RuntimeError: inconsistent tensor sizes at /opt/conda/conda 
bld/pytorch_1503966894950/work/torch/lib/THC/generic/THCTensorMath.cu:141

**Comment by fitsumreda** [comment]
you have to specify `crop_size` and `inference_size` to values evenly divisible by 64. For `inference_size`, you can also specify [-1,-1], and the data loader will calculate and load images/flows with largest possible valid sizes that are less than input image sizes.
Another way around this is to upsample your images/flows to the smallest possible valid sizes that are greater than the input image/flow sizes, and downsample the output of the networks to the original image sizes.
