### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by javlonbek97** [NVIDIA/flownet2-pytorch#287]
I need help to implement this code but I have been failing for a long time. What parts of the code should be changed in order to be compatible with this:
Cuda compilation tools, release 12.1, V12.1.66

>>> print(torch.__version__)
2.0.0+cu117

NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1

**Comment by stha-prashant** [comment]
> I need help to implement this code but I have been failing for a long time. What parts of the code should be changed in order to be compatible with this: Cuda compilation tools, release 12.1, V12.1.66
> 
> > > > print(torch.**version**)
> > > > 2.0.0+cu117
> 
> NVIDIA-SMI 530.30.02 Driver Version: 530.30.02 CUDA Version: 12.1

hi how did you get it to work?

**Comment by sabitarajbanshi** [comment]
> I need help to implement this code but I have been failing for a long time. What parts of the code should be changed in order to be compatible with this: Cuda compilation tools, release 12.1, V12.1.66
> 
> > > > print(torch.**version**)
> > > > 2.0.0+cu117
> 
> NVIDIA-SMI 530.30.02 Driver Version: 530.30.02 CUDA Version: 12.1

hi, I too have been stuck in this for long time. Did you get it work? Please tell me how?
