### ISSUE TITLE
FlowNet2SD single output is wrong

### ISSUE THREAD

**Issue by heurainbow** [NVIDIA/flownet2-pytorch#37]
https://github.com/NVIDIA/flownet2-pytorch/blob/master/models.py/#L340 should be division instead of product.

    return self.upsample1(flow2/self.div_flow)

This can be verified by https://github.com/NVIDIA/flownet2-pytorch/blob/master/models.py/#L156

**Comment by fitsumreda** [comment]
This is fine. You may compare FlownNetSD's EPEs on Sintel that you may get when using division vs multiplication.  

for the flownet2, it was done that way to mimic the behaviour of the original caffe implementation
