### ISSUE TITLE
Can I remove the "grad_output.is_contiguous() == True"?

### ISSUE THREAD

**Issue by PkuRainBow** [NVIDIA/flownet2-pytorch#39]
I meet a bug informed that that grad_output.is_contiguous()=False with in the correlation.py. So can I comment this line? What the influence of this line?

```

def backward(self, grad_output):

   input1, input2 = self.saved_tensors
  
   assert(grad_output.is_contiguous() == True)
```

**Comment by JiamingSuen** [comment]
One option is to make it contiguous if it's not:
```
        if not grad_output.is_contiguous():
            grad_output = grad_output.contiguous()
```
But I'm not quite sure if this would introduce any influence on the `grad_output`(theoretically not..). Maybe the author would explain why `assert` is used instead of just make it contiguous.

**Comment by PkuRainBow** [comment]
@JiamingSuen Your suggestion seems does not work.....   It seems that the grad_output can not be changed to contiguous.

**Comment by Feynman27** [comment]
I also came across this AssertError. The recommendation from @JiamingSuen worked for me. However, why isn't the gradient tensor contiguous to begin with?

**Comment by fitsumreda** [comment]
@JiamingSuen suggestions look fine.
