### ISSUE TITLE
Is there a plan to port the data augmentation layer from caffe to pytorch？

### ISSUE THREAD

**Issue by chenchr** [NVIDIA/flownet2-pytorch#4]
Hello. Thanks for sharing the code. I am training flownet1.0 on flyingchairs using pytorch. However, without data augmentation, overfitting happened. Is there a plan to port the data augmentation layer from caffe to pytorch？As there are so many parameter for differernt kinds of noise for data augmentation, I still can't find a good way to do that.

**Comment by fitsumreda** [comment]
data augmentation is available for random crop only for now.
it should be easy to add the other augmentation methods, though
