### ISSUE TITLE
correlation function runs very slow

### ISSUE THREAD

**Issue by sczhou** [NVIDIA/flownet2-pytorch#40]
Hi, In training the FlowNetC, the correlation layer runs so slow,  It's about 5.5s a batch (batch size = 8) on TiTanX, I don't know whether there are some problems, and could you give me some advice for fast training?  Thanks!

**Comment by fitsumreda** [comment]
@sczhou the issue was that non optimal number of threads per block were used for the backward function of the correlation layer, hence the slow speed.
it is now faster by about 5x.

**Comment by fitsumreda** [comment]
mode details in the commit [`94b023`](https://github.com/NVIDIA/flownet2-pytorch/commit/94b02301d0c28bf0d5ac6be9037b04e9f59f500b)
