### ISSUE TITLE
trying to run in inference mode

### ISSUE THREAD

**Issue by bkvie** [NVIDIA/flownet2-pytorch#41]
Trying to run:
main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /../frame_00 --resume ./checkpoints/flownet2

Results in error:
 File "main.py", line 396, in <module>
    stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
NameError: name 'inference_loader' is not defined

where is inference_loader definded?

**Comment by coderclear** [comment]
I also met this issue. Have you solved?In 251 line of main.py define the 'inference_loader'.

**Comment by 0asa** [comment]
Hi!

Check the `inference_dataset_root` directory. I ran into the same issue, it turned out the path was not accessible/correct. Your directory is `/../frame_00`, it is looking weird, especially the first `/`. Also, if you are using the docker image, make sure to mount the volume accordingly so your image folder is accessible from within the docker image.

**Comment by coderclear** [comment]
if inference_root is  'main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /../frame_00 --resume ./checkpoints/flownet2'.
i got  
NameError: name 'inference_loader' is not defined
if inference_root is  'main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /../training/clean/alley_1 --resume ./checkpoints/flownet2'.
I got 
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range
and 
self.size type is <class 'int'>
self.size is 0
  [0.000s] Operation failed
@0asa

**Comment by fitsumreda** [comment]
@bkvie @coderclear this happens when the inference_dataset_root path doesn't exist.

**Comment by gmy1234** [comment]
Have you solved this problem?

**Comment by gmy1234** [comment]
> 我也遇到了这个问题。解决了吗？在main.py的251行中定义了'inference_loader'。

How do you define it?

**Comment by Sidd1609** [comment]
@fitsumreda I am having this issue despite having a non-empty & existing folder with images that have shape in multiples of 64.

**Comment by coderclear** [comment]
已收到！

**Comment by ruffiann** [comment]
> @fitsumreda I am having this issue despite having a non-empty & existing folder with images that have shape in multiples of 64.

I've noticed that when I process .jpg files it reports a 'list index out of range' error, but works fine when processing .png files. You can try it, hope it helps!

**Comment by coderclear** [comment]
已收到！
