### ISSUE TITLE
Models 

### ISSUE THREAD

**Issue by coderclear** [NVIDIA/flownet2-pytorch#42]
I download models from ''Converted Caffe Pre-trained Models'', but I can not open the model?
When I extracted the file, "An error occurred while loading the archive".
Did anyone come with this issue?

**Comment by bkvie** [comment]
Had the issue, downloading them again, and making sure of the path to file did the trick. 
Maybe provide more error context.
Alternatively use weights from: https://github.com/ClementPinard/FlowNetPytorch

**Comment by JiamingSuen** [comment]
It's actually not a tarball file, it's just the output of `torch.save`, which is a serialized `dict` object.

**Comment by coderclear** [comment]
thanks for your replay, but I have a new issue, like this:
Overall Progress:   0%|                                                       | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 396, in <module>
    stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
NameError: name 'inference_loader' is not defined
@JiamingSuen

**Comment by fitsumreda** [comment]
this happens when `inference_dataset_root` points to an empty folder or it doesn't exist.

**Comment by coderclear** [comment]
I had solved this issue，thank you all .
