### ISSUE TITLE
Torch multiprocessing in docker

### ISSUE THREAD

**Issue by 0asa** [NVIDIA/flownet2-pytorch#43]
I encountered the following Error: 
```
Error : RuntimeError: unable to write to file </torch_18693_1954506624> at /pytorch/torch/lib/TH/THAllocator.c:271
```
Adding the flag `--ipc=host` in the last line in the `launch-docker.sh` right after `sudo nvidia-docker run` fixed the issue.

See pytorch [README.md](https://github.com/pytorch/pytorch/blob/master/README.md): 

> Please note that PyTorch uses shared memory to share data between processes, so if torch multiprocessing is used (e.g. for multithreaded data loaders) the default shared memory segment size that container runs with is not enough, and you should increase shared memory size either with `--ipc=host` or `--shm-size` command line options to nvidia-docker run.

**Comment by fitsumreda** [comment]
thanks @0asa ! I've added your suggestions to the `launch-docker.sh` script.
