### ISSUE TITLE
confirm！correlation layer backward is extremely slow

### ISSUE THREAD

**Issue by cc786537662** [NVIDIA/flownet2-pytorch#45]
I tried three experiments：
A：model without any correlation function
B：model A +  only correlation layer forward
C：model A + both correlation layer forward and backward

ON UBUNTU14+TITAN XP with CUDA8.0，time costed per iteration（including forward and backward）：
A：0.6
B：0.63
C：4.18

so，it seems that the backward of the correlation layer   is extremely slow，and i don't get it why，since  the forward seems pretty good，did anyone know how to accelerate the  backward of the correlation layer ？

**Comment by fitsumreda** [comment]
@cc786537662 thanks for doing the analysis.
it turns out the number of threads per block were not optimal for backward pass of the correlation layer.
with better settings, it is now 5x faster!

**Comment by fitsumreda** [comment]
[94b023](https://github.com/NVIDIA/flownet2-pytorch/commit/94b02301d0c28bf0d5ac6be9037b04e9f59f500b)

**Comment by cc786537662** [comment]
@fitsumreda excellent job ! 
with better setting as you changed in commit 94b023,
now the  experiment result turns out to be：
A：0.6
B：0.63
C：0.826
this is really amazing，thanks again！

**Comment by hamed-d** [comment]
Hey, would it be possible for someone to confirm this?
I've tried training the network on the following configs:
Windows 10:
- CUDA10.1 + torch1.4 + py37
- CUDA9.2 + torch1.4 + py37
- CUDA9.2 + torch0.4.1+ py37

Ubuntu 18.04:
- CUDA10.1 + torch1.4 + py36
- CUDA9.2 + torch1.4 + py36
- CUDA9.2 + torch0.4.1 + py36

The backward times are the same regardless of the OS or the framework versions and it's about 5-7 seconds on average but when the correlation layers are frozen the backward time decreases to 0.3-0.6 seconds. In there a specific combination of CUDA and python versions that I need to run on?
