### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by HTLife** [NVIDIA/flownet2-pytorch#46]
I met some problem when I tried to run the code under python3.

If the code only supports python2 right now, how can I upgrade it?
```
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import FlowNetC
  File "/notebooks/data/vinet/FlowNetC.py", line 8, in <module>
    from correlation_package.modules.correlation import Correlation
  File "/notebooks/data/vinet/correlation_package/modules/correlation.py", line 3, in <module>
    from ..functions.correlation import CorrelationFunction
  File "/notebooks/data/vinet/correlation_package/functions/correlation.py", line 3, in <module>
    from .._ext import correlation
  File "/notebooks/data/vinet/correlation_package/_ext/correlation/__init__.py", line 3, in <module>
    from ._correlation import lib as _lib, ffi as _ffi
ImportError: /notebooks/data/vinet/correlation_package/_ext/correlation/_correlation.so: undefined symbol: PyInt_FromLong
```

**Comment by HTLife** [comment]
@TusharNimbhorkar Thanks for your tips.
Could you load that pre-trained weight by python3 successfully?

**Comment by TusharNimbhorkar** [comment]
@HTLife  
Haven't tried it yet. But I am training from the start and inference step seems to be working for that.

**Comment by HTLife** [comment]
Got it!  That's another solution.  Thanks again.

**Comment by fitsumreda** [comment]
I’m looking at this.

**Comment by fitsumreda** [comment]
i've added a python3 branch.

**Comment by fitsumreda** [comment]
https://github.com/NVIDIA/flownet2-pytorch/tree/python36

**Comment by HTLife** [comment]
@fitsumreda How many memory(main/GPU) is required to train flownet2-pytorch?

- My main memory size: 32GB
- GPU memory: 11GB

I got this error message when I tried to train the network.
```
Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).                        | 0/130.0 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 407, in <module>
    validation_loss, _ = train(args=args, epoch=epoch - 1, start_iteration=global_iteration, data_loader=validation_loader, model=model_and_loss, optimizer=optimizer, logger=validation_logger, is_validate=True, offset=offset)
  File "main.py", line 260, in train
    for batch_idx, (data, target) in enumerate(progress):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 910, in __iter__
    for obj in iterable:
  File "/notebooks/data/flownet2-pytorch/utils/tools.py", line 111, in __next__
    n = next(self.iterator)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.5/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1361) is killed by signal: Bus error.
```

**Comment by HTLife** [comment]
I found the solution for the error above.  It's caused by docker setting.  
Docker should be run with `--shm-size` command
```
sudo nvidia-docker run --shm-size 8G .........
```

Relative discussion could be found at:
1. [Bus error (core dumped) model share memory #2244](https://github.com/pytorch/pytorch/issues/2244#issuecomment-318864552)
2. [possible deadlock in dataloader #1355](https://github.com/pytorch/pytorch/issues/1355#issuecomment-308511534)

**Comment by lcf000000** [comment]
> I met this error when loading pre-trained weight from python3
> 
> ```
> Traceback (most recent call last):                                              
>   File "main.py", line 270, in <module>                                         
>     main()                                                                      
>   File "main.py", line 262, in main                                             
>     train(EPOCH, model, optimizer, BATCH)                                       
>   File "main.py", line 176, in train                                            
>     output = model(data)                                                        
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line
>  357, in __call__                                                               
>     result = self.forward(*input, **kwargs)                                     
>   File "main.py", line 128, in forward                                          
>     c_out = self.flownetc(c_in)                                                 
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line
>  357, in __call__                                                               
>     result = self.forward(*input, **kwargs)                                     
>   File "/notebooks/data/jacky/VINet/FlowNetC.py", line 106, in forward          
>     concat5 = torch.cat((out_conv5,out_deconv5,flow6_up),1)                     
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimensio
> n 1. Got 18 and 17 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMat
> h.cu:111 
> ```

I met the same problem, did you solve it?
