### ISSUE TITLE
Size of tensors does not match Inference Step.

### ISSUE THREAD

**Issue by TusharNimbhorkar** [NVIDIA/flownet2-pytorch#47]
The command I used for inference step. 

`python main.py --crop_size 384 512  --inference --model FlowNet2C --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /home/tushar/data/tushar/MPI-Sintel-post/training --resume ./work/FlowNet2C_train-checkpoint.pth.tar
`

And terminal Screenshot

![image](https://user-images.githubusercontent.com/6749360/38301630-6e27fae8-3800-11e8-8756-78c3e0081d22.png)

**Comment by TusharNimbhorkar** [comment]
Found out why is this error happening. 

During inference step. cropping/resizing is skipped out. And Inference step only take the image size that you trained on.

**Comment by fitsumreda** [comment]
--inference_size must be evenly divisible by 64.
![image](https://user-images.githubusercontent.com/15355345/38444384-d3923110-39a3-11e8-984e-5a4734a04dc3.png)
480 and 854 are not divisible evenly by 64.
if you pass --inference_size -1 -1, then the closest size evenly divisible by 64 will be cropped from your source images, in your case the mpi sintel files
