### ISSUE TITLE
run bash install.sh error

### ISSUE THREAD

**Issue by Zhuysheng** [NVIDIA/flownet2-pytorch#52]
Compiling correlation kernels by nvcc...
In file included from /home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _correlation.c:493:
/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zhuyisheng/anaconda3/envs/py27/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by fitsumreda** [comment]
@Zhuysheng , can you give more information about your environment where you run the install.sh?

**Comment by Qianli-ion** [comment]
Hi @Zhuysheng  and @clarkren !
It seems like this issue can be addressed by creating a symbolic link from your cuda-8.0 directory to /usr/local/cuda. Try this (my cuda is installed at /usr/local/cuda-8.0 you can replace with yours),
`sudo ln -s /usr/local/cuda-8.0 /usr/local/cuda`
At least it address the installation problem for me.

**Comment by fitsumreda** [comment]
@clarkren, @Zhuysheng,
Did you try to use the dockerfile in the repo?
That may help debug the cuda environment issue.

**Comment by Zhuysheng** [comment]
@Qianli-ion it solved my install problem,thanks

**Comment by Qianli-ion** [comment]
Hi @clarkren 

It seems like the error you get right now is not the "cuda.h" problem. So I guess that symbolic link does solve your "cuda.h" problem? 

Now regarding the new problem. From the error you get "‘for’ loop initial declarations are only allowed in C99 mode", it seems like to solve it you can try to add -std=c99 flag in your compilation script. I don't have this problem during my installation so I'm not 100% sure. Have you checked out this post, https://stackoverflow.com/questions/29338206/error-for-loop-initial-declarations-are-only-allowed-in-c99-mode? 

If that couldn't solve the problem it might be worthy to open a new issue if you don't mind. (since it is a new installation issue at the end).

**Comment by ShashiAdhikari** [comment]
> @Qianli-ion it solved my install problem,thanks

Hi @Qianli-ion  how did you solve the issue?
I try running the bash install.sh. 
Error that is commands 'x86_64 -linux-gnc-gcc' failed with exit status 1
can you explain how to run it will be helpful.
Thank you
