### ISSUE TITLE
Validation_Epochs

### ISSUE THREAD

**Issue by JensPeter92** [NVIDIA/flownet2-pytorch#59]
Hi,
When i skip the training and want to validate my test data with an already trained model, 
I´ve got the problem that the validation is depended on the default epochs.
I don´t get it, because the validation should not change with further epochs.

When i e.g. train a model with 10000 epochs and want to validate it straightforward,
Is there any possibility to disable the epochs for validation and enable it for training?

**Comment by JensPeter92** [comment]
Oh I guess I know my mistake.
There is no evaluation of the network implemented, isn´t it?

**Comment by fitsumreda** [comment]
Use —inference mode.
It basically does a validation of your dataset has a ground truth optical flow. Otherwise it will do a simple inference run
