### ISSUE TITLE
Problem with training Flownet2S

### ISSUE THREAD

**Issue by Meghana4** [NVIDIA/flownet2-pytorch#61]
Trying to train Flownet2S using following command.
python main.py  --model FlowNet2S --save_flow --training_dataset  MpiSintelClean --training_dataset_root /home/meghanabasavaraj/Desktop/Meghana/Flownet/flownet2-master/scripts/ --resume ./../FlowNet2-S_checkpoint.pth.tar --batch_size 1 --skip_validation --loss=L1Loss --optimizer_lr=1e-4 --optimizer=Adam
Error:
File "/home/meghanabasavaraj/Desktop/Meghana/RNN/Flow/Reference/flownet2-pytorch-master/flownet2-pytorch/losses.py", line 23, in forward
    lossvalue = torch.abs(output - target).mean()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 442, in __rsub__
    return -self + other
RuntimeError: add() received an invalid combination of arguments - got (tuple), but expected one of:
 * (float other, float alpha)
 * (Variable other, float alpha)

Exception KeyError: KeyError(<weakref at 0x7f2ac6868db8; to 'tqdm' at 0x7f2ac6654990>,) in <bound method tqdm.__del__ of Training Epoch 0:   0%|                                                                      | 0/1041.0 [00:01<?, ?it/s]> ignored
Exception KeyError: KeyError(<weakref at 0x7f2ac6868db8; to 'tqdm' at 0x7f2ac6654250>,) in <bound method tqdm.__del__ of Overall Progress:   0%|                                                   | 0/10001 [00:01<?, ?it/s]> ignored

**Comment by wjbKimberly** [comment]
Hi, I met the same issue. Have you solved it? Could you be so kind to share me the solution?

**Comment by Meghana4** [comment]
Use this command

# Example on MPISintel Final and Clean, with MultiScale loss on FlowNet2C model
python main.py --batch_size 8 --model FlowNet2C --optimizer=Adam
--optimizer_lr=1e-4 --loss=MultiScale --loss_norm=L1 \
--loss_numScales=5 --loss_startScale=4 --optimizer_lr=1e-4 --crop_size 384 512 \
--training_dataset FlyingChairs --training_dataset_root
/path/to/flying-chairs/dataset  \
--validation_dataset MpiSintelClean --validation_dataset_root
/path/to/mpi-sintel/clean/dataset

**Comment by wjbKimberly** [comment]
Thanks a lot for this kind reply!
