### ISSUE TITLE
Strange results with inference

### ISSUE THREAD

**Issue by gbarl** [NVIDIA/flownet2-pytorch#65]
pretrained FlowNet2 runs beautifully when using the command line and ImagesFromFolder argument.  The output flow looks as expected

However when I try to do a single forward pass with the same pretrained network in a notebook with the input of shape (1,3,2,x,y) everything runs smoothly but the output flow looks very off.

Are there any differences in how your DataLoader presents the images that could be the cause?

img1
![input_1_1](https://user-images.githubusercontent.com/29712128/40882155-3d85749e-668e-11e8-8493-62dfc39cb9e6.png)

img2
![input_1_2](https://user-images.githubusercontent.com/29712128/40882156-41ea994c-668e-11e8-8460-0c1d2412f416.png)

flow

![image](https://user-images.githubusercontent.com/29712128/40882151-21037f3c-668e-11e8-967a-0078b1fc1b09.png)

Thanks

**Comment by gbarl** [comment]
RESOLVED:  I was reading in images using matplotlib.pyplot.imread.  Using scipy.misc.imread as in frame_utils.py and then converting to FloatTensor resolved the issue.

**Comment by Larry-u** [comment]
> RESOLVED: I was reading in images using matplotlib.pyplot.imread. Using scipy.misc.imread as in frame_utils.py and then converting to FloatTensor resolved the issue.

Hi, gbarl. How do you manage to test two images in jupyter notebook? Could you share your notebook file? I am confusing about the inference codes...

**Comment by Larry-u** [comment]
@gbarl Hi, gbarl. How do you manage to test two images in jupyter notebook? Could you share your notebook file? I am confusing about the inference codes...
