### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by shanyuhu** [NVIDIA/flownet2-pytorch#69]
One question about the provided pretrained models.
Are all these provided models are pretrained on FlyingChairs and then Flyingthings 3D?
![mode](https://user-images.githubusercontent.com/15082681/42408802-18980e76-8204-11e8-9362-4a55e32bd465.png)

**Comment by fitsumreda** [comment]
Yes. These are obtained by converting the Caffe pre-trained weights provided by the paper authors.
