### ISSUE TITLE
undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by changshuangzhao** [NVIDIA/flownet2-pytorch#79]
ImportError: /home/dell/.conda/envs/py3/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

**Comment by fitsumreda** [comment]
Could you check if there is a mismatch in pytorch version.
Master supports Pytorch v0.4.1
Other branches support 0.4.0 and earlier versions

**Comment by bkvie** [comment]
same issue, torch version 0.4.1

**Comment by xiaofanglegoc** [comment]
I have the same issue, my torch version is 0.4.1

**Comment by HPL123** [comment]
@guancheng817 @xiaofanglegoc @bkvie , did you solve it?

**Comment by alecalma** [comment]
Anyone solved the error with version 0.4.1?

**Comment by pranaypratyush** [comment]
Has this problem been resolved?
