### ISSUE TITLE
ImportError: /home/dell/.conda/envs/py3/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by changshuangzhao** [NVIDIA/flownet2-pytorch#80]
dell@dell:~/device/flownet2-pytorch-master$ python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /path/to/mpi-sintel/clean/dataset --resume /path/to/checkpoints 

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "/home/dell/device/flownet2-pytorch-master/models.py", line 8, in <module>
    from networks.resample2d_package.resample2d import Resample2d
  File "/home/dell/device/flownet2-pytorch-master/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: /home/dell/.conda/envs/py3/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

Why？？Could you help me??

**Comment by fitsumreda** [comment]
Could you check if there is a mismatch in pytorch version?
Master supports Pytorch v0.4.1
Other branches support 0.4.0 and earlier versions

**Comment by changshuangzhao** [comment]
My Pytorch version is 0.4.1, 
Cuda compilation tools, release 8.0, V8.0.61
