### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by amjltc295** [NVIDIA/flownet2-pytorch#88]
I could not complie with the new install.sh. Here is a part of the errors (similar for the three setup.py):
```c
(...)
/usr/local/cuda/bin/nvcc -I/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/lib/pythoe3.7/site-packages/torch/lib/include -I/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/li /python
3.7/site-packages/torch/lib/include/TH -I/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/master/07/yaliangchang/
miniconda3/envs/Shift-Net_pytorch/include/python3.7m -c channelnorm_kernel.cu -o build/temp.linux-x86_64-3.7/channelnorm_kernel.o -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode
arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70 -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
/usr/include/c++/6/tuple: In instantiation of ‘otatic constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonym
us> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:626:248:   required by substitution of ‘template<class ... _UElemen:s, typename std::enable_if<(((std:_ITC<(sizeof... (_UElements) == 1), at::Tensor, at::Tentor, at::Tensor>::_NotSameTu
le<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tens
or, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tu
ple<at::Tensor, at::Tensor, at::Tensor>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_U
Elements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UEle
ments ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h:646:36:   required from here
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/usr/include/c++/6/tuple:484:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Te
n                                                                 ‘                                                                                                                                              n
sor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_ImplicitlyMoveConvertibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool
                                              ‘
<anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:626:362:   required by substitution of ‘tem’ate<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTu
p                                                               ‘                                                                                                                                                p
le<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tens
or, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tu
ple<at::Tensor, at::Tensor, at::Tensor>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_U
Elements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UEle
ments ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h:646:36:   required from here
/usr/include/c++/6/tuple:489:65: error: mismatched argument pack lengths while expanding ‘std::is_convertible<_UElements&&, _Elements>’
       return __and_<is_convertible<_UElements&&, _Elements>...>::value;
                                                                 ^~~~~
/usr/include/c++/6/tuple:490:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_ImplicitlyMoveConvertibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor
,                                                                 ‘                                                                                                                                              ,
 at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<at::Tensor, at::Tensor, at::Tensor>&; bool <anonymous>
                                              ‘
= true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:662:419:   required by substitut’n of ‘template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tens
o                                                               ‘                                                                                                                                                o
r>::_ConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>:
:value && (1ul == 1)), at::Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<const tuple<_Elements ...>&>()), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple<_Ar
gs1 ...>&) [with _UElements = {at::Tensor, at::Tensor, at::Tensor}; _Dummy = void; typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ConstructibleTuple<_UE
lements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), at::
Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<const tuple<_Elements ...>&>()), bool>::type <anonymous> = <missing>]’
/home/master/07/yaliangchang/miniconda3/envs/Shift-Net_pytorch/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h:646:36:   required from here
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (4, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
(...)
```

```bash
$ gcc --version
gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```bash
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

**Comment by zhuhaozh** [comment]
**I think I meet the same problem, except for nvcc version is 9.1. Is your problem solved?**  

/usr/include/c++/6/tuple:489:65: error: mismatched argument pack lengths while expanding ‘std::is_convertible<_UElements&&, _Elements>’


/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = const std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’:
/usr/include/c++/6/tuple:686:422:   required by substitution of ‘template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&) [with _UElements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}; _Dummy = void; typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), at::Tensor, at::Tensor, at::Tensor, at::Tensor>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> = <missing>]’
/home/zhuhao/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Functions.h:3493:99:   required from here
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (5, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/include/c++/6/type_traits:1558:8: note: provided for ‘template<class _From, class _To> struct std::is_convertible’
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by xiaofanglegoc** [comment]
I have exactly the same issue

**Comment by jprouty** [comment]
Me too!

**Comment by jprouty** [comment]
I got path this by trying it with CUDA 9.2 and it seems to have worked!!! Here's my setup.

`python3`
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux

`gcc --version`
gcc (Debian 7.3.0-5) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`nvcc -V`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by PiaCuk** [comment]
I have the same issue.

- Python 3.6.6
- gcc (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
- nvcc: release 9.0, V9.0.176
- PyTorch 0.4.1

Is there any way to get to get past this without installing CUDA 9.2? Has updating to CUDA 9.2 resolved the problem for everyone or just @jprouty ?

**Comment by jprouty** [comment]
I think CUDA 8.0 may also do the trick... I was trying to give vid2vid a spin and was struggling to get setup (with this package specifically). The thing that worked out in the end for me, was to use an nvidia-docker setup. In particular, the vid2vid Dockerfile did the trick for me!

https://github.com/NVIDIA/vid2vid/blob/master/docker/Dockerfile

**Comment by hi0001234d** [comment]
> I think CUDA 8.0 may also do the trick... I was trying to give vid2vid a spin and was struggling to get setup (with this package specifically). The thing that worked out in the end for me, was to use an nvidia-docker setup. In particular, the vid2vid Dockerfile did the trick for me!
> 
> https://github.com/NVIDIA/vid2vid/blob/master/docker/Dockerfile

Yeah. Seems to be the only good option at this time because of conflicts between gcc , cuda and tensorflow. Saved my days after digging between different cuda and gcc versions

**Comment by huangbiubiu** [comment]
This error is caused by the conflict between CUDA & g++. CUDA 9.0 and 9.1 only compatible with g++ <= 5.5 (see [here](https://gist.github.com/ax3l/9489132#nvcc) for more information).

So there are 2 solutions to solve the problem:
1. upgrade CUDA to 9.2 or later
2. downgrade gcc to 5.5 or lower

----------------

Because CUDA 9.2 is not supported by TensorFlow now, if upgrade CUDA to CUDA 9.2, you may not be able to use TensorFlow. So I recommend using g++ 5 to compile. Once the compilation is finished, you can change gcc version for CUDA easily.

Here is a step-by-step solution to use lower version g++ to compile.

1. Install gcc and g++ 5.5 (`sudo apt-get install gcc-5 g++-5` on Ubuntu 16.04)
2. Unlink incompatible gcc version for CUDA: `sudo unlink /usr/local/cuda/bin/gcc`
3. Add a softlink to gcc 5 for CUDA: `sudo ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc`
4. Then CUDA will use gcc 5 to compile. Just run `bash install.sh` to compile packages and it should work.

**Comment by amjltc295** [comment]
Thanks, that solves the issue

> This error is caused by the conflict between CUDA & g++. CUDA 9.0 and 9.1 only compatible with g++ <= 5.5 (see [here](https://gist.github.com/ax3l/9489132#nvcc) for more information).
> 
> So there are 2 solutions to solve the problem:
> 
> 1. upgrade CUDA to 9.2 or later
> 2. downgrade gcc to 5.5 or lower
> 
> Because CUDA 9.2 is not supported by TensorFlow now, if upgrade CUDA to CUDA 9.2, you may not be able to use TensorFlow. So I recommend using g++ 5 to compile. Once the compilation is finished, you can change gcc version for CUDA easily.
> 
> Here is a step-by-step solution to use lower version g++ to compile.
> 
> 1. Install gcc and g++ 5.5 (`sudo apt-get install gcc-5 g++-5` on Ubuntu 16.04)
> 2. Unlink incompatible gcc version for CUDA: `sudo unlink /usr/local/cuda/bin/gcc`
> 3. Add a softlink to gcc 5 for CUDA: `sudo ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc`
> 4. Then CUDA will use gcc 5 to compile. Just run `bash install.sh` to compile packages and it should work.
