### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by Yuliang-Zou** [NVIDIA/flownet2-pytorch#9]
Hi, thanks for sharing the code. 

I wonder if you can also share the performance numbers of the pre-trained models on the benchmarks (e.g. KITTI, Sintel, etc.). Seems that you did not use data augmentation, so I am actually quite curious about the performance.

**Comment by PkuRainBow** [comment]
@fitsumreda I am also wondering the whether the performance of this code base can match the caffe version flownet2.  It would be great if you could share us the related experimental numbers.

**Comment by fitsumreda** [comment]
we'll release scripts that downloads and converts flownet2-official (from authors) Caffe pre-trained models to PyTorch, which can be used with --resume argument in this repository
we will also provide information about model training from scratch.

**Comment by fitsumreda** [comment]
we've added instructions that downloads and converts official caffe-pre-trained models to PyTorch.
https://github.com/NVIDIA/flownet2-pytorch#convert-official-caffe-pre-trained-models-to-pytorch

you may use the converted checkpoints with the `--resume` argument in this repository

**Comment by Yuliang-Zou** [comment]
Hi @fitsumreda , thanks for the response. Since installing Caffe on cluster could be messy, can you provide download links for us to get the converted PyTorch models?

Also, I am still curious about the performance (training from scratch using this code, and using converted models with this code).
