### ISSUE TITLE
NameError: name 'inference_loader' is not defined

### ISSUE THREAD

**Issue by 3togo** [NVIDIA/flownet2-pytorch#92]
After running the following comand, I got a NameError: name 'inference_loader' is not defined
Any help?

python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
--inference_dataset_root ~/Downloads/mpi-sintel/training/clean/alley_1 \
--resume ~/checkpoints 

Initializing Adam Optimizer
  [0.002s] amsgrad = False (<class 'bool'>)
  [0.002s] weight_decay = 0 (<class 'int'>)
  [0.002s] eps = 1e-08 (<class 'float'>)
  [0.002s] betas = (0.9, 0.999) (<class 'tuple'>)
  [0.002s] lr = 0.001 (<class 'float'>)
  [0.002s] Operation finished

Overall Progress:   0%|                                                       | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 403, in <module>
    stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
NameError: name 'inference_loader' is not defined
Exception ignored in: <bound method tqdm.__del__ of Overall Progress:   0%|                                                       | 0/1 [00:00<?, ?it/s]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 889, in __del__
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1095, in close
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 441, in _decr_instances
  File "/usr/lib/python3.6/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x7f2f303e6868; to 'tqdm' at 0x7f2f2f4a5a20>

**Comment by 3togo** [comment]
fixed. 

# python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
> --inference_dataset_root /data/MPISintel/training \
> --resume /workspace/flownet2-pytorch/FlowNet2_checkpoint.pth.tar

**Comment by gmy1234** [comment]
> 固定。
> 
> ```
> python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
> > --inference_dataset_root /data/MPISintel/training \
> > --resume /workspace/flownet2-pytorch/FlowNet2_checkpoint.pth.tar
> ```
Still not working

**Comment by gmy1234** [comment]
> fixed.
> 
> ```
> python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
> > --inference_dataset_root /data/MPISintel/training \
> > --resume /workspace/flownet2-pytorch/FlowNet2_checkpoint.pth.tar
> ```



> fixed.
> 
> ```
> python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
> > --inference_dataset_root /data/MPISintel/training \
> > --resume /workspace/flownet2-pytorch/FlowNet2_checkpoint.pth.tar
> ```

After running the following comand, I got a NameError: name 'inference_loader' is not defined
